### PR TITLE
Update PR Gap encoder

### PR DESCRIPTION
**Pull request by alexis-cvetkov**

### CODE REVIEW

**Review by LilianBoulard — APPROVED** [review]
Perfect, thank you !

**Comment by LilianBoulard** [comment]
I'm running the tests and merging :)

**Comment by LilianBoulard** [comment]
Hmm... Weird, I've launched the tests twice, and some tests fail randomly. It always happens in `test_get_feature_names` in GE tests, I checked the code but didn't notice any anomaly.

Error:
```
 >       assert topic_labels_2[0] == 'col0: ' + topic_labels[0]
E       AssertionError: assert 'col0: 1qvfo9..., 092246dlmqc' == 'col0: 1qvfo9...rk, 734340159'
E         - col0: 1qvfo9innc3s, 1qlbrlinn7rk, 734340159
E         ?                                   ^^ ^^^^^^
E         + col0: 1qvfo9innc3s, 1qlbrlinn7rk, 092246dlmqc
E         ?                                   ^^^^ ^^^^^^
```
Any clue ?

**Comment by alexis-cvetkov** [comment]
Yes, actually it is because applying the transform method multiple times in a row on the same input X gives slightly different encodings.

During training we learn the topics W, and during transform we try to fit the activations H so that V = HW, with W being fixed. The fitted activations H are then used as encodings.
However appying `transform` on X doesn't restart that fitting from scratch but start from the previous encodings H. Encodings thus continue to converge when using `transform` multiple times.
In practice the encodings almost don't change, but in rares cases it is enough to change the topic labels between iterations of `transform`on the same input X.
I can easily make it work in the test by retraining a new encoder each time and calling `transform` just once, but maybe we want `transform` to always give the same output over calls ? @GaelVaroquaux

**Comment by GaelVaroquaux** [comment]
We need to rework the tests to be more robust, so that the failure observed by @LilianBoulard doesn't happen. Maybe a slightly lower dimensional problem (less input features)?

**Comment by alexis-cvetkov** [comment]
Changing the number of input features won't remove the problem I think. In rares cases, we could still have the tests failing.
Maybe it's not a issue if calling `transform` multiple times in a row slightly changes the encodings. For now I made the tests work properly by setting the random_state to a seed for which the topic labels don't change between calls of `get_feature_names` (which internally calls `transform`).

**Comment by GaelVaroquaux** [comment]
> In rares cases, we could still have the tests failing.

OK, let's open an issue to keep it in mind and move on for now.

**Comment by alexis-cvetkov** [comment]
I have added a side note in the docstring of `transform` to indicate that this behaviour is normal and not an issue in itself.
I have also created an issue to remind us: https://github.com/dirty-cat/dirty_cat/issues/188
Seems good to merge !

**Pull request merged**
